### ISSUE TITLE
ArduinoLowPower not working (put in Incompatible list)

### ISSUE THREAD

**Issue by piercalderan** [arduino-libraries/ArduinoLowPower#33]
Hi, I tried to compile the example with UNO, Leonardo SAMD21 cards
Not working with 1.8.13 IDE. Maybe works on older IDEs?
Best regards

**Comment by aentinger** [comment]
It should work with `samd`, compatibility with `avr` (i.e. Uno or Leonardo) is already ruled out via the `architectures` statement within [library.properties](https://github.com/arduino-libraries/ArduinoLowPower/blob/master/library.properties#L9).
