### ISSUE TITLE
library.properties broken library link

### ISSUE THREAD

**Issue by smellai** [arduino-libraries/ArduinoLowPower#4]
url=http://arduino.cc/libraries/ArduinoLowPower

**Comment by jfcaron3** [comment]
Confirmed, the "More info" link in the Arduino IDE Library Manager window goes to a 404 error.

**Comment by q2dg** [comment]
And the link in Web Editor too

**Comment by per1234** [comment]
The link now redirects to the Arduino Low Power library's reference page at:
https://www.arduino.cc/en/Reference/ArduinoLowPower
so this can be closed as fixed (I don't have the permissions in this repo to close it).
